# Configuração para o Render.com
services:
  - type: web
    name: ponto-eletronico
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URI
        value: sqlite:///instance/ponto_eletronico.db
      - key: DEBUG
        value: false
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
